<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('pengerjaan_model');
        $this->load->model('perbaikan_model');
        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }
    }

    public function index()
    {
        $data=array(
        'category'  => $this->perbaikan_model->ambil_data(),
        'catsiram2015'  => set_value('catsiram2015',$this->pengerjaan_model->ambil_data_perbaikan_2015()),
        'catsiram2016'  => set_value('catsiram2016',$this->pengerjaan_model->ambil_data_perbaikan_2016()),
        'catsiram2017'  => set_value('catsiram2017',$this->pengerjaan_model->ambil_data_perbaikan_2017()));
		$this->load->view('home',$data);
        
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */