<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Signin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('customer_login_model');
    }

    public function index()
    {
		if($this->session->userdata('customer_logined') && $this->session->userdata('customer_logined') == true)
		{
			redirect('pengerjaan_customer');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('customer_login');
		}
		else
		{
			$cek_login=$this->customer_login_model->cek_login_customer(
				$this->input->post('username'),
				$this->input->post('password')
				);
			if(!empty($cek_login))
			{
				$this->session->set_userdata('customer_logined', true);
				$this->session->set_userdata('customer_username', $cek_login->username);
				redirect("pengerjaan_customer");
			}
			else 
			{
				redirect("Signin");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('customer_logined');
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */